### PR TITLE
Close #204, #205 search improvement

### LINKED ISSUE #204: search -> esteem toggle in search mode
Currently, once search something, toggle back to esteem mode is impossible, which is quite annoying if you want to go to someone's blog. I'll fix this.

### PR DESCRIPTION
**Pull request by economicstudio**
Close #204, #205 

- #204: search -> esteem toggle in search mode
- #205: esteem first before search for query starting with @

### CODE REVIEW

**Comment by feruzm** [comment]
Thanks @economicstudio for PR, looking good... Can I ask you to separate `@` related change? Because that should probably be about finding accounts names and starting `#` should be about finding tags. Steem API has search for tags and accounts which can be utilized in this case and all other queries can use eSteem Search as usual. @talhasch please check this or work on separate PR with @economicstudio ...

**Comment by feruzm** [comment]
You can always use `author` and `tag` keywords for search.. Our search engine is quite advanced, we only need to show some tips for user when they start typing or when they type `hint`
image

By using `@`, I was referring to autocomplete/autosuggestions rather than search, sorry I could've been more clearer. Once user select autocomplete options (search results from Steem API), we can navigate to user profile like you initially suggested. Same goes for `#` key, when autocomplete is selected, open example `trending/#tag` = `trending/tag` = `trending/esteem`. @talhasch will followup soon with his thoughts, I will ping him on discord...

**Comment by talhasch** [comment]
@economicstudio as @feruzm referred our search engine is very advanced and you can filter contents by author and tag filters. i could not clearly understand which side you wanted to improve? user filtering by username?

**Comment by talhasch** [comment]
@economicstudio currently we have username support for address bar. for example when you enter `@ned` to address bar and enter it takes you to `@ned`'s blog.

Anyways, we decided to implement an auto complete functionality to address bar for users and tags. Closing this one. Thanks for your efforts&feedbacks.

**Comment by feruzm** [comment]
@economicstudio please leave only toggle functionality and we can merge that part for now.

**Comment by economicstudio** [comment]
@talhasch No problem, but you didn't understand my point. (I mean even in search mode, it should direct to blog, not search result) But anyway thanks for your comment and look forward to seeing the autocomplete feature :) Thanks.

@feruzm Thanks will do!

**Pull request closed without merging**
